# Generated by Django 3.0.4 on 2020-03-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_auto_20200311_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'verbose_name': '书目', 'verbose_name_plural': '书目'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book', verbose_name='书号'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Student', verbose_name='学号'),
        ),
    ]
