# Generated by Django 3.0.4 on 2020-03-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0004_auto_20200312_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='book',
            new_name='book_id',
        ),
    ]
