# Generated by Django 3.0.4 on 2020-03-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0005_auto_20200312_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='student_id',
            new_name='student',
        ),
    ]
