# Generated by Django 3.0.4 on 2020-03-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0007_auto_20200312_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='User',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='student',
            new_name='user',
        ),
    ]
