# Generated by Django 3.0.4 on 2020-03-21 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0011_auto_20200317_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['id'], 'verbose_name': '借阅关系表', 'verbose_name_plural': '借阅关系表'},
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='borrow_date',
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrow_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 10, 31, 52, 344053), verbose_name='借出时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_ddl',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 10, 31, 52, 344095), verbose_name='归还期限'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('action', models.CharField(max_length=30, verbose_name='操作')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book', verbose_name='所借书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylibrary.User', verbose_name='借阅者')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'ordering': ['id'],
            },
        ),
    ]
