# Generated by Django 3.0.4 on 2020-03-21 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0012_auto_20200321_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 10, 42, 57, 511300), verbose_name='借出时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_ddl',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 10, 42, 57, 511365), verbose_name='归还期限'),
        ),
        migrations.AlterField(
            model_name='log',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mylibrary.Book', verbose_name='所借书籍'),
        ),
    ]
